// 香港 42 间酒店完整数据集与客房元数据（价格已校准并严格对齐基础房型）
const hotelsData = [
    {
        "id": 1,
        "name": "香港唯港荟酒店 (Hotel ICON)",
        "enName": "Hotel ICON Hong Kong",
        "district": "尖沙咀",
        "location": "九龙尖沙咀东部科学馆道17号",
        "distance": "距离尖东站步行约4分钟，临近维港海滨",
        "stars": 5,
        "rating": 9.4,
        "reviewCount": 4280,
        "verdict": "超棒极佳",
        "dealTag": "限时特惠 78折",
        "price": 1480,
        "originalPrice": 1880,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "icon-101",
                "name": "ICON 36 经典城市客房",
                "size": "36 平方米",
                "bed": "1张特大双人床 (King Bed)",
                "bathroom": "独立干湿分离卫浴 (带步入式淋浴间)",
                "breakfast": "含双人精致自助早餐",
                "cancel": "入住前24小时可免费取消",
                "price": 1480,
                "origPrice": 1880,
                "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "icon-102",
                "name": "CLUB 36 全海景行政客房",
                "size": "38 平方米",
                "bed": "1张特大床 或 2张单人床",
                "bathroom": "独立大理石卫浴 (带全景浴缸与淋浴)",
                "breakfast": "含行政酒廊全日礼遇及自助早餐",
                "cancel": "入住前24小时可免费取消",
                "price": 2180,
                "origPrice": 2780,
                "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 2,
        "name": "香港瑰丽酒店 (Rosewood Hong Kong)",
        "enName": "Rosewood Hong Kong",
        "district": "尖沙咀",
        "location": "九龙尖沙咀梳士巴利道18号 Victoria Dockside",
        "distance": "坐落尖沙咀海滨核心，直通K11 MUSEA",
        "stars": 5,
        "rating": 9.7,
        "reviewCount": 2680,
        "verdict": "传奇顶奢",
        "dealTag": "黑卡尊享礼遇",
        "price": 4680,
        "originalPrice": 5880,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "rw-201",
                "name": "九龙景观尊贵大理石客房",
                "size": "53 平方米",
                "bed": "1张特大双人床 (Custom King)",
                "bathroom": "独立双台盆奢华大理石卫浴 (带独立浸泡浴缸)",
                "breakfast": "含 Holt's Cafe 奢华半自助早餐",
                "cancel": "入住前48小时可免费取消",
                "price": 4680,
                "origPrice": 5880,
                "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "rw-202",
                "name": "尊尚维港海景大套房",
                "size": "78 平方米",
                "bed": "1张特大床 / 独立会客起居室",
                "bathroom": "独立维港景观大理石浴室 (双人水疗浴缸)",
                "breakfast": "含 Manor Club 贵宾酒廊早餐及香槟茶歇",
                "cancel": "不可退款优惠特价",
                "price": 6800,
                "origPrice": 8500,
                "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 3,
        "name": "香港芬名酒店 (The Fleming Hong Kong)",
        "enName": "The Fleming Boutique Hotel",
        "district": "湾仔",
        "location": "港岛湾仔菲林明道41号",
        "distance": "距离湾仔地铁站步行约3分钟，近香港会展中心",
        "stars": 4,
        "rating": 9.0,
        "reviewCount": 1820,
        "verdict": "复古潮流精品",
        "dealTag": "设计师甄选",
        "price": 1180,
        "originalPrice": 1480,
        "hasBreakfast": true,
        "hasPool": false,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "fl-301",
                "name": "雅致小号双人房 (渡轮美学风)",
                "size": "22 平方米",
                "bed": "1张标准双人床 (Queen Bed)",
                "bathroom": "独立复古黄铜卫浴 (配热带雨林花洒)",
                "breakfast": "不含早餐 (可现场加购意式早餐)",
                "cancel": "入住前24小时可免费取消",
                "price": 1180,
                "origPrice": 1480,
                "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "fl-302",
                "name": "经典中型尊贵房 (附工作吧台)",
                "size": "26 平方米",
                "bed": "1张大床 (King Bed)",
                "bathroom": "独立干湿分离浴室",
                "breakfast": "含 Osteria Marzia 地道意式双人早餐",
                "cancel": "入住前24小时可免费取消",
                "price": 1450,
                "origPrice": 1820,
                "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 4,
        "name": "香港帝苑酒店 (The Royal Garden)",
        "enName": "The Royal Garden Hotel",
        "district": "尖沙咀",
        "location": "九龙尖沙咀东么地道69号",
        "distance": "尖东繁华商圈，步行至星光大道约6分钟",
        "stars": 5,
        "rating": 8.9,
        "reviewCount": 5120,
        "verdict": "经典五星",
        "dealTag": "早鸟特惠 8折",
        "price": 1080,
        "originalPrice": 1380,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "rg-401",
                "name": "尊贵豪华客房 (中庭花园景)",
                "size": "30 平方米",
                "bed": "1张大床 或 2张单人床",
                "bathroom": "独立大理石卫浴 (带独立浴缸)",
                "breakfast": "含帝苑饼店招牌双人欧陆早餐套餐",
                "cancel": "入住前24小时可免费取消",
                "price": 1080,
                "origPrice": 1380,
                "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "rg-402",
                "name": "天际地中海露台客房",
                "size": "36 平方米",
                "bed": "1张特大双人床 (King Bed)",
                "bathroom": "独立大理石干湿分离卫浴",
                "breakfast": "含雅苑座国际双人自助早餐",
                "cancel": "入住前48小时可免费取消",
                "price": 1480,
                "origPrice": 1880,
                "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 5,
        "name": "香港置地文华东方酒店 (The Landmark Mandarin Oriental)",
        "enName": "The Landmark Mandarin Oriental",
        "district": "中环",
        "location": "港岛中环皇后大道中15号置地广场",
        "distance": "中环核心金融区，直通中环地铁站",
        "stars": 5,
        "rating": 9.6,
        "reviewCount": 2190,
        "verdict": "顶级奢华",
        "dealTag": "热卖推荐",
        "price": 4500,
        "originalPrice": 5600,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-5-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "58 平方米",
                "bed": "1张特大双人床",
                "bathroom": "独立超大圆形浸泡浴缸及干湿分离卫浴",
                "breakfast": "含双人米其林星厨定制早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 4500,
                "origPrice": 5600,
                "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-5-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "66 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 6075,
                "origPrice": 7560,
                "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 6,
        "name": "香港四季酒店 (Four Seasons Hotel Hong Kong)",
        "enName": "Four Seasons Hotel Hong Kong",
        "district": "中环",
        "location": "港岛中环金融街8号国际金融中心",
        "distance": "直通IFC商场与机场快线香港站",
        "stars": 5,
        "rating": 9.5,
        "reviewCount": 3450,
        "verdict": "卓越尊贵",
        "dealTag": "会员专享价",
        "price": 4800,
        "originalPrice": 6000,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-6-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "45 平方米",
                "bed": "1张特大双人床 / 全景维港窗景",
                "bathroom": "独立大理石水疗浴室 (配镜面电视浴缸)",
                "breakfast": "含双人四季丰盛自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 4800,
                "origPrice": 6000,
                "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-6-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "53 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 6480,
                "origPrice": 8100,
                "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 7,
        "name": "香港半岛酒店 (The Peninsula Hong Kong)",
        "enName": "The Peninsula Hong Kong",
        "district": "尖沙咀",
        "location": "九龙尖沙咀梳士巴利道22号",
        "distance": "百年传奇地标，直面维多利亚港",
        "stars": 5,
        "rating": 9.7,
        "reviewCount": 4800,
        "verdict": "百年传奇",
        "dealTag": "热卖推荐",
        "price": 4980,
        "originalPrice": 6280,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-7-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "48 平方米",
                "bed": "1张豪华特大床",
                "bathroom": "独立大理石卫浴 (配水疗情绪灯光浴缸)",
                "breakfast": "含半岛经典大堂双人早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 4980,
                "origPrice": 6280,
                "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-7-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "56 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 6720,
                "origPrice": 8480,
                "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 8,
        "name": "香港奕居 (The Upper House)",
        "enName": "The Upper House",
        "district": "金钟",
        "location": "港岛金钟道88号太古广场",
        "distance": "坐落太古广场高层，俯瞰金钟港湾",
        "stars": 5,
        "rating": 9.6,
        "reviewCount": 1890,
        "verdict": "都市静谧奢华",
        "dealTag": "会员专享价",
        "price": 4200,
        "originalPrice": 5200,
        "hasBreakfast": true,
        "hasPool": false,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-8-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "68 平方米",
                "bed": "1张特大双人床 (配全景落地窗)",
                "bathroom": "独立豪华水疗浴室 (配备无敌海景石灰岩浴缸)",
                "breakfast": "含 Salisterra 景观餐厅精选早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 4200,
                "origPrice": 5200,
                "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-8-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "76 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 5670,
                "origPrice": 7020,
                "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 9,
        "name": "香港美利酒店 (The Murray, Hong Kong, a Niccolo Hotel)",
        "enName": "The Murray, Hong Kong, a Niccolo Hotel",
        "district": "中环",
        "location": "港岛中环红棉路22号",
        "distance": "近山顶缆车站与香港公园，历史建筑改造",
        "stars": 5,
        "rating": 9.2,
        "reviewCount": 2760,
        "verdict": "超棒极佳",
        "dealTag": "热卖推荐",
        "price": 2650,
        "originalPrice": 3350,
        "hasBreakfast": true,
        "hasPool": false,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-9-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "47 平方米",
                "bed": "1张特大床 / 标志性嵌入式大窗",
                "bathroom": "独立云石卫浴 (带独立蛋形浴缸与淋浴)",
                "breakfast": "含 The Tai Pan 双人半自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 2650,
                "origPrice": 3350,
                "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-9-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "55 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 3575,
                "origPrice": 4520,
                "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 10,
        "name": "香港JW万豪酒店 (JW Marriott Hotel Hong Kong)",
        "enName": "JW Marriott Hotel Hong Kong",
        "district": "金钟",
        "location": "港岛金钟道88号太古广场",
        "distance": "直通金钟四线换乘核心枢纽地铁站",
        "stars": 5,
        "rating": 9.1,
        "reviewCount": 3890,
        "verdict": "豪华商务",
        "dealTag": "会员专享价",
        "price": 2250,
        "originalPrice": 2850,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-10-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "33 平方米",
                "bed": "1张大床 或 2张单人床",
                "bathroom": "独立干湿分离卫浴",
                "breakfast": "含双人JW咖啡室国际自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 2250,
                "origPrice": 2850,
                "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-10-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "41 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 3037,
                "origPrice": 3847,
                "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 11,
        "name": "香港港丽酒店 (Conrad Hong Kong)",
        "enName": "Conrad Hong Kong",
        "district": "金钟",
        "location": "港岛金钟道88号太古广场二座",
        "distance": "太古广场顶层，视野开阔俯瞰维港",
        "stars": 5,
        "rating": 9.0,
        "reviewCount": 3100,
        "verdict": "优质五星",
        "dealTag": "热卖推荐",
        "price": 2180,
        "originalPrice": 2750,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-11-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "40 平方米",
                "bed": "1张特大双人床",
                "bathroom": "独立大理石卫浴 (带独立浴缸)",
                "breakfast": "含双人丰富自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 2180,
                "origPrice": 2750,
                "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-11-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "48 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 2940,
                "origPrice": 3710,
                "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 12,
        "name": "香港丽思卡尔顿酒店 (The Ritz-Carlton Hong Kong)",
        "enName": "The Ritz-Carlton Hong Kong",
        "district": "西九龙",
        "location": "九龙柯士甸道西1号环球贸易广场102-118层",
        "distance": "全球最高酒店之一，九龙站ICC直达",
        "stars": 5,
        "rating": 9.6,
        "reviewCount": 4120,
        "verdict": "云端奢享",
        "dealTag": "会员专享价",
        "price": 4100,
        "originalPrice": 5200,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-12-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "50 平方米",
                "bed": "1张特大双人床 / 110层云端天际景",
                "bathroom": "独立全景大理石卫浴 (配浸泡浴缸)",
                "breakfast": "含双人云端全景自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 4100,
                "origPrice": 5200,
                "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-12-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "58 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 5535,
                "origPrice": 7020,
                "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 13,
        "name": "香港W酒店 (W Hong Kong)",
        "enName": "W Hong Kong",
        "district": "西九龙",
        "location": "九龙柯士甸道西1号圆方Elements",
        "distance": "直通九龙站与机场快线，邻近西九文化区",
        "stars": 5,
        "rating": 9.0,
        "reviewCount": 3680,
        "verdict": "时尚潮流",
        "dealTag": "热卖推荐",
        "price": 2280,
        "originalPrice": 2880,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-13-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "40 平方米",
                "bed": "1张标志性W特色大床",
                "bathroom": "独立时尚卫浴 (配水疗淋浴及独立浴缸)",
                "breakfast": "含 Kitchen 餐厅双人活力早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 2280,
                "origPrice": 2880,
                "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-13-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "48 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 3078,
                "origPrice": 3888,
                "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 14,
        "name": "香港嘉里酒店 (Kerry Hotel Hong Kong)",
        "enName": "Kerry Hotel Hong Kong",
        "district": "红磡",
        "location": "九龙红磡湾红鸾道38号",
        "distance": "坐拥无遮挡红磡维港海滨，紧邻黄埔站",
        "stars": 5,
        "rating": 9.2,
        "reviewCount": 3340,
        "verdict": "度假首选",
        "dealTag": "会员专享价",
        "price": 1880,
        "originalPrice": 2380,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-14-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "42 平方米",
                "bed": "1张特大床 / 超大海景阳台视角",
                "bathroom": "独立大理石干湿分离卫浴",
                "breakfast": "含大湾咖啡厅丰富自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1880,
                "origPrice": 2380,
                "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-14-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "50 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 2538,
                "origPrice": 3213,
                "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 15,
        "name": "香港朗廷酒店 (The Langham Hong Kong)",
        "enName": "The Langham Hong Kong",
        "district": "尖沙咀",
        "location": "九龙尖沙咀北京道8号",
        "distance": "紧邻海港城与广东道奢品街，地理位置极佳",
        "stars": 5,
        "rating": 9.1,
        "reviewCount": 4100,
        "verdict": "欧式典雅",
        "dealTag": "热卖推荐",
        "price": 1780,
        "originalPrice": 2280,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-15-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "32 平方米",
                "bed": "1张特大双人床",
                "bathroom": "独立大理石浴室 (配经典爪足浴缸)",
                "breakfast": "含双人 The Food Gallery 早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1780,
                "origPrice": 2280,
                "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-15-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "40 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 2403,
                "origPrice": 3078,
                "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 16,
        "name": "香港马哥孛罗香港酒店 (Marco Polo Hongkong Hotel)",
        "enName": "Marco Polo Hongkong Hotel",
        "district": "尖沙咀",
        "location": "九龙尖沙咀广东道3号海港城",
        "distance": "直通海港城商场，天星码头旁",
        "stars": 5,
        "rating": 8.7,
        "reviewCount": 3920,
        "verdict": "地段优越",
        "dealTag": "会员专享价",
        "price": 1280,
        "originalPrice": 1650,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-16-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "30 平方米",
                "bed": "1张大床 或 2张单人床",
                "bathroom": "独立卫浴 (带淋浴及浴缸)",
                "breakfast": "含双人马哥孛罗咖啡厅早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1280,
                "origPrice": 1650,
                "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-16-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "38 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1728,
                "origPrice": 2228,
                "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 17,
        "name": "香港九龙香格里拉大酒店 (Kowloon Shangri-La)",
        "enName": "Kowloon Shangri-La",
        "district": "尖沙咀",
        "location": "九龙尖沙咀东部么地道64号",
        "distance": "近尖东站，直面维多利亚港夜景",
        "stars": 5,
        "rating": 9.0,
        "reviewCount": 3780,
        "verdict": "经典典雅",
        "dealTag": "热卖推荐",
        "price": 1750,
        "originalPrice": 2250,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-17-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "42 平方米",
                "bed": "1张特大床 (超大客房空间)",
                "bathroom": "独立豪华大理石卫浴",
                "breakfast": "含双人 Cafe Kool 国际自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1750,
                "origPrice": 2250,
                "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-17-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "50 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 2362,
                "origPrice": 3037,
                "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 18,
        "name": "香港君悦酒店 (Grand Hyatt Hong Kong)",
        "enName": "Grand Hyatt Hong Kong",
        "district": "湾仔",
        "location": "港岛湾仔港湾道1号",
        "distance": "直通香港会议展览中心与会展站",
        "stars": 5,
        "rating": 9.3,
        "reviewCount": 3600,
        "verdict": "商务奢华",
        "dealTag": "会员专享价",
        "price": 2880,
        "originalPrice": 3600,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-18-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "40 平方米",
                "bed": "1张豪华特大床",
                "bathroom": "独立大理石卫浴 (带智能镜及浴缸)",
                "breakfast": "含 Grand Cafe 丰盛双人早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 2880,
                "origPrice": 3600,
                "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-18-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "48 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 3888,
                "origPrice": 4860,
                "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 19,
        "name": "香港铜锣湾皇冠假日酒店 (Crowne Plaza Causeway Bay)",
        "enName": "Crowne Plaza Causeway Bay",
        "district": "铜锣湾",
        "location": "港岛铜锣湾礼顿道8号",
        "distance": "对望跑马地马场，步行至时代广场3分钟",
        "stars": 5,
        "rating": 8.9,
        "reviewCount": 2450,
        "verdict": "城市核心",
        "dealTag": "热卖推荐",
        "price": 1450,
        "originalPrice": 1850,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-19-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "34 平方米",
                "bed": "1张大床 或 2张单人床",
                "bathroom": "独立玻璃干湿分离卫浴",
                "breakfast": "含顶楼俱乐部景观自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1450,
                "origPrice": 1850,
                "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-19-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "42 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1957,
                "origPrice": 2497,
                "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 20,
        "name": "香港柏宁铂尔曼酒店 (The Park Lane Hong Kong, a Pullman Hotel)",
        "enName": "The Park Lane Hong Kong, a Pullman Hotel",
        "district": "铜锣湾",
        "location": "港岛铜锣湾告士打道310号",
        "distance": "正对维多利亚公园，临近铜锣湾地铁站",
        "stars": 5,
        "rating": 8.8,
        "reviewCount": 3850,
        "verdict": "现代活力",
        "dealTag": "会员专享价",
        "price": 1380,
        "originalPrice": 1780,
        "hasBreakfast": true,
        "hasPool": false,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-20-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "30 平方米",
                "bed": "1张特大双人床",
                "bathroom": "独立现代卫浴 (带雨淋花洒)",
                "breakfast": "含 PLAYT 丰富自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1380,
                "origPrice": 1780,
                "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-20-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "38 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1863,
                "origPrice": 2403,
                "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 21,
        "name": "香港富豪香港酒店 (Regal Hongkong Hotel)",
        "enName": "Regal Hongkong Hotel",
        "district": "铜锣湾",
        "location": "港岛铜锣湾怡和街88号",
        "distance": "铜锣湾购物商圈核心，欧陆古典风格",
        "stars": 5,
        "rating": 8.5,
        "reviewCount": 2900,
        "verdict": "经典便利",
        "dealTag": "热卖推荐",
        "price": 980,
        "originalPrice": 1280,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-21-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "28 平方米",
                "bed": "1张双人床 或 2张单人床",
                "bathroom": "独立卫浴 (配标准浴缸)",
                "breakfast": "含双人御花园咖啡室早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 980,
                "origPrice": 1280,
                "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-21-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "36 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1323,
                "origPrice": 1728,
                "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 22,
        "name": "香港旺角康得思酒店 (Cordis, Hong Kong)",
        "enName": "Cordis, Hong Kong",
        "district": "旺角",
        "location": "九龙旺角上海街555号",
        "distance": "直通朗豪坊商场及旺角地铁站，吃喝极度便利",
        "stars": 5,
        "rating": 9.2,
        "reviewCount": 5400,
        "verdict": "地标首选",
        "dealTag": "会员专享价",
        "price": 1480,
        "originalPrice": 1880,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-22-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "32 平方米",
                "bed": "1张大床 或 2张单人床",
                "bathroom": "独立大理石卫浴 (配大浴缸与独立淋浴间)",
                "breakfast": "含 The Place 知名双人自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1480,
                "origPrice": 1880,
                "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-22-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "40 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1998,
                "origPrice": 2538,
                "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 23,
        "name": "香港帝京酒店 (Royal Plaza Hotel)",
        "enName": "Royal Plaza Hotel",
        "district": "旺角",
        "location": "九龙旺角太子道西193号",
        "distance": "直通新世纪广场商场及旺角东火车站",
        "stars": 5,
        "rating": 9.0,
        "reviewCount": 4980,
        "verdict": "亲子舒适",
        "dealTag": "热卖推荐",
        "price": 1150,
        "originalPrice": 1480,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-23-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "33 平方米",
                "bed": "2张宽敞大床 (适合家庭入住)",
                "bathroom": "独立干湿分离卫浴 (带浴缸)",
                "breakfast": "含双人花月庭自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1150,
                "origPrice": 1480,
                "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-23-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "41 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1552,
                "origPrice": 1998,
                "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 24,
        "name": "香港千禧新世界香港酒店 (New World Millennium Hong Kong)",
        "enName": "New World Millennium Hong Kong",
        "district": "尖沙咀",
        "location": "九龙尖沙咀东么地道72号",
        "distance": "尖东海旁，距离红磡站步行约6分钟",
        "stars": 5,
        "rating": 8.9,
        "reviewCount": 3200,
        "verdict": "海滨优选",
        "dealTag": "会员专享价",
        "price": 1350,
        "originalPrice": 1750,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-24-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "35 平方米",
                "bed": "1张特大双人床",
                "bathroom": "独立大理石卫浴 (配卫洗丽及浴缸)",
                "breakfast": "含双人东来顺风格特色早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1350,
                "origPrice": 1750,
                "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-24-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "43 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1822,
                "origPrice": 2362,
                "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 25,
        "name": "香港尖沙咀凯悦酒店 (Hyatt Regency Hong Kong, Tsim Sha Tsui)",
        "enName": "Hyatt Regency Hong Kong, Tsim Sha Tsui",
        "district": "尖沙咀",
        "location": "九龙尖沙咀河内道18号 K11",
        "distance": "直通K11商场与尖沙咀/尖东双地铁站",
        "stars": 5,
        "rating": 9.0,
        "reviewCount": 3900,
        "verdict": "枢纽便利",
        "dealTag": "热卖推荐",
        "price": 1680,
        "originalPrice": 2180,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-25-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "31 平方米",
                "bed": "1张大床 (King Bed)",
                "bathroom": "独立干湿分离卫浴",
                "breakfast": "含咖啡厅双人精选自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1680,
                "origPrice": 2180,
                "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-25-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "39 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 2268,
                "origPrice": 2943,
                "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 26,
        "name": "香港沙田凯悦酒店 (Hyatt Regency Hong Kong, Sha Tin)",
        "enName": "Hyatt Regency Hong Kong, Sha Tin",
        "district": "沙田",
        "location": "新界沙田泽祥街18号",
        "distance": "临近港铁大学站，依山傍海绿意度假风",
        "stars": 5,
        "rating": 8.9,
        "reviewCount": 2800,
        "verdict": "山海度假",
        "dealTag": "会员专享价",
        "price": 1180,
        "originalPrice": 1480,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-26-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "38 平方米",
                "bed": "1张特大床 (九肚山景/吐露港景)",
                "bathroom": "独立大理石干湿分离卫浴",
                "breakfast": "含双人沙田咖啡厅自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1180,
                "origPrice": 1480,
                "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-26-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "46 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1593,
                "origPrice": 1998,
                "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 27,
        "name": "香港沙田万怡酒店 (Courtyard by Marriott Hong Kong Sha Tin)",
        "enName": "Courtyard by Marriott Hong Kong Sha Tin",
        "district": "沙田",
        "location": "新界沙田安平街1号",
        "distance": "城门河畔，临近石门站，性价比极高",
        "stars": 4,
        "rating": 8.7,
        "reviewCount": 3100,
        "verdict": "舒适商务",
        "dealTag": "热卖推荐",
        "price": 820,
        "originalPrice": 1080,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-27-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "27 平方米",
                "bed": "1张大床 或 2张单人床",
                "bathroom": "独立现代淋浴间",
                "breakfast": "含双人 MoMo Cafe 自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 820,
                "origPrice": 1080,
                "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-27-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "35 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1107,
                "origPrice": 1458,
                "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 28,
        "name": "香港沙田帝都酒店 (Royal Park Hotel)",
        "enName": "Royal Park Hotel",
        "district": "沙田",
        "location": "新界沙田白鹤汀街8号",
        "distance": "直通新城市广场大型购物中心与沙田站",
        "stars": 4,
        "rating": 8.8,
        "reviewCount": 3600,
        "verdict": "购物便捷",
        "dealTag": "会员专享价",
        "price": 880,
        "originalPrice": 1150,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-28-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "30 平方米",
                "bed": "1张大床 或 2张单人床",
                "bathroom": "独立干湿分离卫浴",
                "breakfast": "含双人 2+2 Cafe 自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 880,
                "origPrice": 1150,
                "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-28-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "38 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1188,
                "origPrice": 1552,
                "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 29,
        "name": "香港诺富特世纪酒店 (Novotel Century Hong Kong)",
        "enName": "Novotel Century Hong Kong",
        "district": "湾仔",
        "location": "港岛湾仔谢斐道238号",
        "distance": "湾仔美食区中心，步行至会展中心约8分钟",
        "stars": 4,
        "rating": 8.6,
        "reviewCount": 2900,
        "verdict": "法式连锁",
        "dealTag": "热卖推荐",
        "price": 860,
        "originalPrice": 1120,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-29-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "23 平方米",
                "bed": "1张标准双人床",
                "bathroom": "独立现代卫浴",
                "breakfast": "含 Le Cafe 双人自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 860,
                "origPrice": 1120,
                "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-29-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "31 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1161,
                "origPrice": 1512,
                "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 30,
        "name": "香港百乐酒店 (Park Hotel Hong Kong)",
        "enName": "Park Hotel Hong Kong",
        "district": "尖沙咀",
        "location": "九龙尖沙咀漆咸道南61-65号",
        "distance": "尖沙咀核心区，周边餐饮购物密集",
        "stars": 4,
        "rating": 8.6,
        "reviewCount": 3300,
        "verdict": "出行便捷",
        "dealTag": "会员专享价",
        "price": 790,
        "originalPrice": 1020,
        "hasBreakfast": false,
        "hasPool": false,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-30-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "25 平方米",
                "bed": "1张大床 或 2张单人床",
                "bathroom": "独立干湿分离卫浴",
                "breakfast": "不含早餐 (可于入住时自选加购)",
                "cancel": "入住前24小时内可免费取消",
                "price": 790,
                "origPrice": 1020,
                "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-30-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "33 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1066,
                "origPrice": 1377,
                "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 31,
        "name": "香港湾仔睿景酒店 (Kew Green Hotel Wanchai)",
        "enName": "Kew Green Hotel Wanchai",
        "district": "湾仔",
        "location": "港岛湾仔轩尼诗道41-49号",
        "distance": "紧邻太古广场三座与湾仔站，交通四通八达",
        "stars": 4,
        "rating": 8.7,
        "reviewCount": 2400,
        "verdict": "英伦简约",
        "dealTag": "热卖推荐",
        "price": 760,
        "originalPrice": 980,
        "hasBreakfast": false,
        "hasPool": false,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-31-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "21 平方米",
                "bed": "1张标准双人床",
                "bathroom": "独立英伦格调卫浴",
                "breakfast": "不含早餐 (可于入住时自选加购)",
                "cancel": "入住前24小时内可免费取消",
                "price": 760,
                "origPrice": 980,
                "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-31-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "29 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1026,
                "origPrice": 1323,
                "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 32,
        "name": "香港中环荷李活道木的地酒店 (Madera Hollywood)",
        "enName": "Madera Hollywood",
        "district": "中环",
        "location": "港岛中环荷李活道53-55号",
        "distance": "中环SoHo苏豪区，好莱坞复古精品设计",
        "stars": 4,
        "rating": 9.1,
        "reviewCount": 1420,
        "verdict": "复古精品套房",
        "dealTag": "会员专享价",
        "price": 1580,
        "originalPrice": 1980,
        "hasBreakfast": true,
        "hasPool": false,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-32-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "54 平方米",
                "bed": "1房1厅全套房 (配微波炉与客厅)",
                "bathroom": "独立奢华干湿分离浴室",
                "breakfast": "含每日欧陆早餐送到客房",
                "cancel": "入住前24小时内可免费取消",
                "price": 1580,
                "origPrice": 1980,
                "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-32-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "62 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 2133,
                "origPrice": 2673,
                "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 33,
        "name": "香港宜必思中上环酒店 (ibis Hong Kong Central & Sheung Wan)",
        "enName": "ibis Hong Kong Central & Sheung Wan",
        "district": "上环",
        "location": "港岛上环德辅道西28号",
        "distance": "上环码头及电车总站旁，高层开阔海景",
        "stars": 3,
        "rating": 8.5,
        "reviewCount": 4600,
        "verdict": "超高性价比",
        "dealTag": "热卖推荐",
        "price": 580,
        "originalPrice": 750,
        "hasBreakfast": false,
        "hasPool": false,
        "hasCancel": true,
        "hasGym": false,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-33-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "17 平方米",
                "bed": "1张标准大床 (直面维港部分海景)",
                "bathroom": "独立模块化淋浴卫浴",
                "breakfast": "不含早餐 (可于入住时自选加购)",
                "cancel": "入住前24小时内可免费取消",
                "price": 580,
                "origPrice": 750,
                "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-33-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "25 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 783,
                "origPrice": 1012,
                "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 34,
        "name": "香港华丽海景酒店 (Best Western Plus Hotel Hong Kong)",
        "enName": "Best Western Plus Hotel Hong Kong",
        "district": "西营盘",
        "location": "港岛西营盘德辅道西308号",
        "distance": "港铁西营盘站旁，高楼层视野宽阔",
        "stars": 4,
        "rating": 8.2,
        "reviewCount": 2800,
        "verdict": "经济实用",
        "dealTag": "会员专享价",
        "price": 490,
        "originalPrice": 650,
        "hasBreakfast": false,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-34-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "19 平方米",
                "bed": "1张标准双人床",
                "bathroom": "独立私人卫浴 (带淋浴间)",
                "breakfast": "不含早餐 (可于入住时自选加购)",
                "cancel": "入住前24小时内可免费取消",
                "price": 490,
                "origPrice": 650,
                "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-34-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "27 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 661,
                "origPrice": 877,
                "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 35,
        "name": "香港北角维港凯悦尚萃酒店 (Hyatt Centric Victoria Harbour)",
        "enName": "Hyatt Centric Victoria Harbour",
        "district": "北角",
        "location": "港岛北角北角邨里1号",
        "distance": "直面东区维港海景，顶楼无边际泳池超网红",
        "stars": 5,
        "rating": 9.3,
        "reviewCount": 4400,
        "verdict": "网红无边际海景",
        "dealTag": "热卖推荐",
        "price": 1450,
        "originalPrice": 1850,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-35-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "31 平方米",
                "bed": "1张特大双人床 / 180度纯海景落地窗",
                "bathroom": "独立现代卫浴 (配备品牌水疗备品)",
                "breakfast": "含 The Farmhouse 双人自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1450,
                "origPrice": 1850,
                "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-35-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "39 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1957,
                "origPrice": 2497,
                "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 36,
        "name": "香港东隅酒店 (EAST Hong Kong)",
        "enName": "EAST Hong Kong",
        "district": "鲗鱼涌",
        "location": "港岛太古城太古城道29号",
        "distance": "直通太古城中心商场与太古站，现代轻奢风",
        "stars": 4,
        "rating": 9.1,
        "reviewCount": 2600,
        "verdict": "潮流设计",
        "dealTag": "会员专享价",
        "price": 1280,
        "originalPrice": 1620,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-36-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "28 平方米",
                "bed": "1张特大床 (配恐龙蛋泡澡浴缸)",
                "bathroom": "独立干湿分离大理石浴室",
                "breakfast": "含 FEAST 双人活力早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1280,
                "origPrice": 1620,
                "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-36-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "36 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1728,
                "origPrice": 2187,
                "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 37,
        "name": "香港数码港艾美酒店 (Le Meridien Hong Kong, Cyberport)",
        "enName": "Le Meridien Hong Kong, Cyberport",
        "district": "薄扶林",
        "location": "港岛数码港道100号",
        "distance": "南区海景绿意环抱，远离喧嚣宠物友好",
        "stars": 5,
        "rating": 8.9,
        "reviewCount": 1750,
        "verdict": "南区悠闲",
        "dealTag": "热卖推荐",
        "price": 1280,
        "originalPrice": 1650,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-37-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "35 平方米",
                "bed": "1张特大双人床 (全智能客房控制)",
                "bathroom": "独立大理石卫浴 (带深浸泡浴缸)",
                "breakfast": "含 South Island 双人海景早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1280,
                "origPrice": 1650,
                "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-37-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "43 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1728,
                "origPrice": 2228,
                "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 38,
        "name": "香港海洋公园万豪酒店 (Hong Kong Ocean Park Marriott Hotel)",
        "enName": "Hong Kong Ocean Park Marriott Hotel",
        "district": "黄竹坑",
        "location": "港岛黄竹坑黄竹坑道180号",
        "distance": "港铁海洋公园站直达，超大礁湖泳池亲子度假",
        "stars": 5,
        "rating": 9.2,
        "reviewCount": 3800,
        "verdict": "亲子度假首选",
        "dealTag": "会员专享价",
        "price": 1580,
        "originalPrice": 2080,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-38-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "38 平方米",
                "bed": "2张双人床 / 礁湖泳池景观",
                "bathroom": "独立干湿分离卫浴 (配儿童洗漱包)",
                "breakfast": "含海湾餐厅丰富亲子自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1580,
                "origPrice": 2080,
                "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-38-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "46 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 2133,
                "origPrice": 2808,
                "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 39,
        "name": "香港富丽敦海洋公园酒店 (The Fullerton Ocean Park Hotel)",
        "enName": "The Fullerton Ocean Park Hotel",
        "district": "黄竹坑",
        "location": "港岛香港仔海洋径3号",
        "distance": "全海景度假五星酒店，无边际海景泳池",
        "stars": 5,
        "rating": 9.3,
        "reviewCount": 2900,
        "verdict": "南区奢华海滨",
        "dealTag": "热卖推荐",
        "price": 2350,
        "originalPrice": 3100,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-39-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "40 平方米",
                "bed": "1张特大双人床 / 南中国海壮阔海景",
                "bathroom": "独立奢华全海景卫浴 (带观景浴缸)",
                "breakfast": "含星耀厅全海景双人自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 2350,
                "origPrice": 3100,
                "image": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-39-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "48 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 3172,
                "origPrice": 4185,
                "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 40,
        "name": "香港东涌世茂喜来登酒店 (Sheraton Hong Kong Tung Chung Hotel)",
        "enName": "Sheraton Hong Kong Tung Chung Hotel",
        "district": "东涌",
        "location": "新界大屿山东涌怡东路9号",
        "distance": "近香港国际机场与港珠澳大桥，附免费穿梭巴士",
        "stars": 5,
        "rating": 9.0,
        "reviewCount": 3100,
        "verdict": "机场度假首选",
        "dealTag": "会员专享价",
        "price": 1280,
        "originalPrice": 1650,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-40-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "35 平方米",
                "bed": "1张特大双人床 (大屿山海景)",
                "bathroom": "独立大理石干湿分离卫浴",
                "breakfast": "含屿坊双人丰盛自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1280,
                "origPrice": 1650,
                "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-40-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "43 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1728,
                "origPrice": 2228,
                "image": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 41,
        "name": "香港天际万豪酒店 (Hong Kong SkyCity Marriott Hotel)",
        "enName": "Hong Kong SkyCity Marriott Hotel",
        "district": "赤鱲角",
        "location": "新界赤鱲角香港国际机场航天城东路1号",
        "distance": "紧邻亚洲国际博览馆与机场，看演唱会首选",
        "stars": 5,
        "rating": 8.9,
        "reviewCount": 3600,
        "verdict": "博览会与航运",
        "dealTag": "热卖推荐",
        "price": 1380,
        "originalPrice": 1750,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "room-41-1",
                "name": "标准精选客房 (Superior Room)",
                "size": "35 平方米",
                "bed": "1张特大双人床 或 2张单人床",
                "bathroom": "独立大理石干湿分离卫浴",
                "breakfast": "含天际咖啡厅双人自助早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 1380,
                "origPrice": 1750,
                "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "room-41-2",
                "name": "豪华景观客房 (Deluxe Premier View)",
                "size": "43 平方米",
                "bed": "1张特大双人床 (King Bed) / 尊享高楼层视野",
                "bathroom": "独立干湿分离大理石卫浴 (带独立深浸浴缸)",
                "breakfast": "含双人特色现做营养早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 1863,
                "origPrice": 2362,
                "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
            }
        ]
    },
    {
        "id": 42,
        "name": "香港维港朗廷汇酒店 (The Grand Harbourside Langham Hong Kong)",
        "enName": "The Grand Harbourside Langham Hong Kong",
        "district": "中环",
        "location": "港岛中环民耀街88号中环海滨综合体",
        "distance": "紧邻中环天星码头与摩天轮，直通IFC与中环站",
        "stars": 5,
        "rating": 9.8,
        "reviewCount": 1580,
        "verdict": "传奇云端奢华",
        "dealTag": "黑卡尊享礼遇",
        "price": 4980,
        "originalPrice": 6280,
        "hasBreakfast": true,
        "hasPool": true,
        "hasCancel": true,
        "hasGym": true,
        "hasPrivateBath": true,
        "images": [
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
        ],
        "rooms": [
            {
                "id": "ghl-4201",
                "name": "天际尊尚维港全景客房 (Grand Skyline Harbour Room)",
                "size": "58 平方米",
                "bed": "1张特大双人床 (Custom King Bed)",
                "bathroom": "独立进口白玛瑙奢华水疗卫浴 (配落地窗景双人浴缸与智能淋浴系统)",
                "breakfast": "含双人米其林星厨定制点单式奢华早餐",
                "cancel": "入住前24小时内可免费取消",
                "price": 4980,
                "origPrice": 6280,
                "image": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=600&q=80"
            },
            {
                "id": "ghl-4202",
                "name": "维港朗廷汇府邸海景套房 (The Grand Harbourside Suite)",
                "size": "92 平方米",
                "bed": "独立起居会客厅 + 特大双人床",
                "bathroom": "独立双台盆大理石浴室 (带蒸汽水疗房与全景浸泡浴缸)",
                "breakfast": "含专属行政贵宾府邸全日香槟茶点与定制早餐",
                "cancel": "入住前48小时内可免费取消",
                "price": 7980,
                "origPrice": 9980,
                "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80"
            }
        ]
    }
];