// restaurants_data.js
const restaurantsData = [
    // ================= 頂級法式 / 當代歐陸料理 (French & Contemporary) =================
    {
        id: 42,
        name: "Caprice (香港四季酒店)",
        district: "中環",
        location: "中環金融街8號香港四季酒店6樓",
        distance: "港鐵香港站步行約3分鐘",
        images: ["https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80"],
        stars: 5,
        rating: 9.8,
        reviewCount: 3420,
        verdict: "傳奇極佳",
        originalPrice: 3200,
        price: 2880,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: true,
        hasVegan: false,
        hasCancel: true,
        menus: [
            { id: "c42_m1", name: "米芝蓮三星 經典法式品鑑 6 道菜晚宴", image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80", style: "傳統法式", drinks: "包含餐酒搭配", seating: "180° 維港全海景席", cancel: "24小時前免費取消", origPrice: 3200, price: 2880 },
            { id: "c42_m2", name: "主廚精選 4 道菜嘗味晚市套餐", image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80", style: "當代法式", drinks: "歡迎香檳一杯", seating: "雅緻散座", cancel: "不可退款", origPrice: 2400, price: 2180 }
        ]
    },
    {
        id: 1,
        name: "L'Envol (香港瑞吉酒店)",
        district: "灣仔",
        location: "灣仔港灣徑1號香港瑞吉酒店3樓",
        distance: "港鐵會展站步行約5分鐘",
        images: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80"],
        stars: 5,
        rating: 9.7,
        reviewCount: 1890,
        verdict: "精緻奢華",
        originalPrice: 2880,
        price: 2580,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: true,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r1_m1", name: "Heritage 8道菜奢華法式晚宴", image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=600&q=80", style: "頂級法式", drinks: "頂級魚子醬品鑑配酒", seating: "尊貴主廳", cancel: "48小時前免費取消", origPrice: 2880, price: 2580 }
        ]
    },
    {
        id: 2,
        name: "Amber (置地文華東方酒店)",
        district: "中環",
        location: "中環皇后大道中15號置地文華東方酒店7樓",
        distance: "港鐵中環站置地廣場出口直達",
        images: ["https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80"],
        stars: 5,
        rating: 9.6,
        reviewCount: 2900,
        verdict: "極高評價",
        originalPrice: 2688,
        price: 2388,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: true,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r2_m1", name: "無乳製品與無麩質 6道菜當代晚宴", image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80", style: "綠星當代法式", drinks: "無酒精發酵特調搭配", seating: "流線型主廳", cancel: "24小時前免費取消", origPrice: 2688, price: 2388 }
        ]
    },
    {
        id: 3,
        name: "ÉPURE",
        district: "尖沙咀",
        location: "尖沙咀廣東道海港城海洋中心4樓403號舖",
        distance: "港鐵尖沙咀站步行約5分鐘",
        images: ["https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.3,
        reviewCount: 1450,
        verdict: "優雅浪漫",
        originalPrice: 2180,
        price: 1980,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: true,
        hasVegan: false,
        hasCancel: true,
        menus: [
            { id: "r3_m1", name: "法國時令黑松露與海鮮品嚐菜單", image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80", style: "當代法式", drinks: "精選勃艮第紅白酒", seating: "露台園景位", cancel: "24小時前免費取消", origPrice: 2180, price: 1980 }
        ]
    },
    {
        id: 4,
        name: "BELON",
        district: "中環",
        location: "中環蘇豪伊利近街1-5號1樓",
        distance: "港鐵中環站步行約8分鐘",
        images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.4,
        reviewCount: 1680,
        verdict: "極高讚譽",
        originalPrice: 2288,
        price: 2088,
        hasPrivateRoom: false,
        hasWindowSeat: false,
        hasParking: false,
        hasVegan: false,
        hasCancel: false,
        menus: [
            { id: "r4_m1", name: "巴黎新派小酒館精緻晚宴菜單", image: "https://images.unsplash.com/photo-1514326640560-7d063ef2aed5?auto=format&fit=crop&w=600&q=80", style: "新派法式", drinks: "自然酒 Pairing", seating: "藍調主吧台卡座", cancel: "特惠不可退", origPrice: 2288, price: 2088 }
        ]
    },
    {
        id: 5,
        name: "Louise (PMQ元創方)",
        district: "中環",
        location: "中環鴨巴甸街35號元創方Jwan棟地下",
        distance: "港鐵上環站步行約7分鐘",
        images: ["https://images.unsplash.com/photo-1578474846511-04ba529f0b88?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.2,
        reviewCount: 1320,
        verdict: "花園秘境",
        originalPrice: 2080,
        price: 1880,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: false,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r5_m1", name: "法式經典傳統烤黃雞與家常奢華菜單", image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80", style: "花園法式", drinks: "特調餐前雞尾酒", seating: "二樓典雅庭院席", cancel: "24小時前免費取消", origPrice: 2080, price: 1880 }
        ]
    },
    {
        id: 6,
        name: "Feuille",
        district: "中環",
        location: "中環威靈頓街198號The Wellington 5樓",
        distance: "港鐵上環站步行約4分鐘",
        images: ["https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.3,
        reviewCount: 980,
        verdict: "自然主義",
        originalPrice: 1980,
        price: 1780,
        hasPrivateRoom: false,
        hasWindowSeat: true,
        hasParking: false,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r6_m1", name: "自然植物與時令海鮮可持續晚市品味套餐", image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80", style: "自然風法餐", drinks: "有機生物動力葡萄酒", seating: "落地玻璃窗座", cancel: "24小時前免費取消", origPrice: 1980, price: 1780 }
        ]
    },

    // ================= 高級粵菜與頂級中菜 (Fine Chinese & Cantonese) =================
    {
        id: 7,
        name: "天龍軒 (香港麗思卡爾頓酒店)",
        district: "西九龍",
        location: "九龍柯士甸道西1號環球貿易廣場102樓",
        distance: "港鐵九龍站步行約2分鐘",
        images: ["https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=800&q=80"],
        stars: 5,
        rating: 9.7,
        reviewCount: 3100,
        verdict: "雲端天際",
        originalPrice: 2488,
        price: 2188,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: true,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r7_m1", name: "主廚劉秉雷至尊鮑魚花膠 6 道菜晚宴", image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80", style: "傳統頂級粵菜", drinks: "二十年陳年普洱及配酒", seating: "102樓極致雲端窗座", cancel: "24小時前免費取消", origPrice: 2488, price: 2188 }
        ]
    },
    {
        id: 8,
        name: "龍景軒 (香港四季酒店)",
        district: "中環",
        location: "中環金融街8號香港四季酒店4樓",
        distance: "港鐵香港站步行約3分鐘",
        images: ["https://images.unsplash.com/photo-1525610553991-2bede1a236e2?auto=format&fit=crop&w=800&q=80"],
        stars: 5,
        rating: 9.6,
        reviewCount: 3600,
        verdict: "米芝蓮傳奇",
        originalPrice: 2680,
        price: 2380,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: true,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r8_m1", name: "龍景軒主廚精選海鮮晚宴套餐", image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80", style: "頂級粵菜", drinks: "茗茶品鑑搭配", seating: "維港正海景席", cancel: "48小時前免費取消", origPrice: 2680, price: 2380 }
        ]
    },
    {
        id: 9,
        name: "唐閣 (香港朗廷酒店)",
        district: "尖沙咀",
        location: "尖沙咀北京道8號香港朗廷酒店1樓及2樓",
        distance: "港鐵尖東站步行約2分鐘",
        images: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80"],
        stars: 5,
        rating: 9.5,
        reviewCount: 2400,
        verdict: "典雅粵饌",
        originalPrice: 2388,
        price: 2088,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: true,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r9_m1", name: "米芝蓮三星 三蔥爆龍蝦招牌晚市盛宴", image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80", style: "傳統粵菜", drinks: "頂級單叢茶", seating: "絲絨典雅主廳", cancel: "24小時前免費取消", origPrice: 2388, price: 2088 }
        ]
    },
    {
        id: 10,
        name: "大班樓 (The Chairman)",
        district: "中環",
        location: "中環威靈頓街198號The Wellington 3樓",
        distance: "港鐵上環站步行約4分鐘",
        images: ["https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80"],
        stars: 5,
        rating: 9.8,
        reviewCount: 4200,
        verdict: "世界頂級",
        originalPrice: 2600,
        price: 2280,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: false,
        hasVegan: false,
        hasCancel: false,
        menus: [
            { id: "r10_m1", name: "雞油花雕蒸大花蟹配陳村粉 經典套餐", image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80", style: "原創粵菜", drinks: "古法無添加配酒", seating: "主雅座", cancel: "預付不可退", origPrice: 2600, price: 2280 }
        ]
    },
    {
        id: 11,
        name: "麗晶軒 (香港麗晶酒店)",
        district: "尖沙咀",
        location: "尖沙咀梳士巴利道18號香港麗晶酒店地下",
        distance: "港鐵尖東站步行約3分鐘",
        images: ["https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.4,
        reviewCount: 1850,
        verdict: "海景美饌",
        originalPrice: 2280,
        price: 1980,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: true,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r11_m1", name: "黑松露脆皮燒鵝與極品海鮮晚市套餐", image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80", style: "精緻粵菜", drinks: "特級侍茶師精選", seating: "無遮擋維港水岸位", cancel: "24小時前免費取消", origPrice: 2280, price: 1980 }
        ]
    },
    {
        id: 12,
        name: "文華廳 (香港文華東方酒店)",
        district: "中環",
        location: "中環干諾道中5號香港文華東方酒店25樓",
        distance: "港鐵中環站步行約2分鐘",
        images: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.3,
        reviewCount: 2200,
        verdict: "高空典雅",
        originalPrice: 2188,
        price: 1888,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: true,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r12_m1", name: "黃洪勝主廚古法重塑 6道菜晚宴", image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80", style: "傳統粵菜", drinks: "文華特調香茗", seating: "25樓俯瞰維港位", cancel: "24小時前免費取消", origPrice: 2188, price: 1888 }
        ]
    },
    {
        id: 13,
        name: "潤 Rùn (香港瑞吉酒店)",
        district: "灣仔",
        location: "灣仔港灣徑1號香港瑞吉酒店2樓",
        distance: "港鐵會展站步行約5分鐘",
        images: ["https://images.unsplash.com/photo-1525610553991-2bede1a236e2?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.4,
        reviewCount: 1420,
        verdict: "精緻當代",
        originalPrice: 2380,
        price: 2080,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: true,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r13_m1", name: "洪志光主廚滋補花膠及松茸品嚐晚宴", image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80", style: "當代粵菜", drinks: "極品鳳凰單叢", seating: "茶藝主廳", cancel: "24小時前免費取消", origPrice: 2380, price: 2080 }
        ]
    },
    {
        id: 14,
        name: "甬府 (Yong Fu)",
        district: "灣仔",
        location: "灣仔駱克道20-24號地下及1樓",
        distance: "港鐵灣仔站步行約4分鐘",
        images: ["https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.5,
        reviewCount: 1650,
        verdict: "極致江浙",
        originalPrice: 2800,
        price: 2480,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: false,
        hasVegan: false,
        hasCancel: true,
        menus: [
            { id: "r14_m1", name: "寧波東海十八斬與野生大黃魚尊享套餐", image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80", style: "頂級寧波菜", drinks: "陳年紹興花雕搭配", seating: "奢華私密包廂席", cancel: "48小時前免費取消", origPrice: 2800, price: 2480 }
        ]
    },

    // ================= 頂級日本料理 / 壽司 Omakase / 割烹 (Japanese Fine Dining) =================
    {
        id: 15,
        name: "鮨·志魂 (Sushi Shikon)",
        district: "中環",
        location: "中環皇后大道中15號置地文華東方酒店7樓",
        distance: "港鐵中環站置地廣場出口直達",
        images: ["https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80"],
        stars: 5,
        rating: 9.8,
        reviewCount: 1980,
        verdict: "壽司殿堂",
        originalPrice: 3500,
        price: 2980,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: true,
        hasVegan: false,
        hasCancel: false,
        menus: [
            { id: "r15_m1", name: "銀座頂級江戶前壽司 Omakase 主廚品鑑", image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=80", style: "江戶前壽司", drinks: "十四代純米大吟釀搭配", seating: "檜木主板前席 (限8席)", cancel: "特惠不可退", origPrice: 3500, price: 2980 }
        ]
    },
    {
        id: 16,
        name: "割烹 凜 (Kappo Rin)",
        district: "中環",
        location: "中環皇后大道中15號置地文華東方酒店7樓",
        distance: "港鐵中環站步行約2分鐘",
        images: ["https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.5,
        reviewCount: 1200,
        verdict: "時令極鮮",
        originalPrice: 2800,
        price: 2400,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: true,
        hasVegan: false,
        hasCancel: true,
        menus: [
            { id: "r16_m1", name: "日本直送時令海鮮與炭火割烹品味料理", image: "https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=600&q=80", style: "當代割烹", drinks: "清酒專門搭配 (4款)", seating: "割烹板前景觀席", cancel: "24小時前免費取消", origPrice: 2800, price: 2400 }
        ]
    },
    {
        id: 17,
        name: "Ryota Kappou Modern",
        district: "中環",
        location: "中環安蘭街18號21樓",
        distance: "港鐵中環站步行約3分鐘",
        images: ["https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.3,
        reviewCount: 950,
        verdict: "現代和風",
        originalPrice: 2380,
        price: 2080,
        hasPrivateRoom: false,
        hasWindowSeat: true,
        hasParking: false,
        hasVegan: false,
        hasCancel: true,
        menus: [
            { id: "r17_m1", name: "和牛與北海道海膽 現代割烹體驗菜單", image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80", style: "現代日式割烹", drinks: "特選日本吟釀", seating: "開放式廚房吧台", cancel: "24小時前免費取消", origPrice: 2380, price: 2080 }
        ]
    },
    {
        id: 18,
        name: "Sushi Wadatsumi",
        district: "尖沙咀",
        location: "尖沙咀梳士巴利道18號K11 MUSEA 6樓",
        distance: "港鐵尖東站直達K11 MUSEA",
        images: ["https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.2,
        reviewCount: 1100,
        verdict: "正宗匠心",
        originalPrice: 2200,
        price: 1980,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: true,
        hasVegan: false,
        hasCancel: true,
        menus: [
            { id: "r18_m1", name: "東京築地直送 主廚Omakase晚宴 (18品)", image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=80", style: "江戶前壽司", drinks: "時令清酒一杯", seating: "壽司主吧台", cancel: "24小時前免費取消", origPrice: 2200, price: 1980 }
        ]
    },
    {
        id: 19,
        name: "GODENYA (燗酒專門)",
        district: "中環",
        location: "中環惠豐閣威靈頓街182號地下",
        distance: "港鐵上環站步行約5分鐘",
        images: ["https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.6,
        reviewCount: 880,
        verdict: "清酒極致",
        originalPrice: 2600,
        price: 2350,
        hasPrivateRoom: false,
        hasWindowSeat: false,
        hasParking: false,
        hasVegan: false,
        hasCancel: false,
        menus: [
            { id: "r19_m1", name: "清酒溫度美學與割烹料理極致 Pairing 盛宴", image: "https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=600&q=80", style: "清酒配餐割烹", drinks: "包含8款精準溫控清酒", seating: "私密日式吧台 (限6席)", cancel: "特惠不可退", origPrice: 2600, price: 2350 }
        ]
    },
    {
        id: 20,
        name: "鑄·鐵板燒 (I M Teppanyaki & Wine)",
        district: "天后",
        location: "天后清風街13號地下",
        distance: "港鐵天后站步行約3分鐘",
        images: ["https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.1,
        reviewCount: 1350,
        verdict: "鐵板盛宴",
        originalPrice: 2180,
        price: 1880,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: false,
        hasVegan: false,
        hasCancel: true,
        menus: [
            { id: "r20_m1", name: "日本頂級 A5 飛驒牛與南非鮑魚鐵板晚市套餐", image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80", style: "日式鐵板燒", drinks: "精選紅酒搭配", seating: "主鐵板表演台席", cancel: "24小時前免費取消", origPrice: 2180, price: 1880 }
        ]
    },

    // ================= 頂級意大利菜 (Italian Fine Dining) =================
    {
        id: 21,
        name: "8 1/2 Otto e Mezzo BOMBANA",
        district: "中環",
        location: "中環遮打道16-20號歷山大廈2樓202號舖",
        distance: "港鐵中環站置地廣場出口直達",
        images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80"],
        stars: 5,
        rating: 9.7,
        reviewCount: 3800,
        verdict: "白松露之王",
        originalPrice: 3100,
        price: 2780,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: true,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r21_m1", name: "米芝蓮三星 經典手工意粉與時令松露品嚐菜單", image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=600&q=80", style: "傳統頂級意式", drinks: "意大利皮埃蒙特產區配酒", seating: "主雕塑水晶大廳", cancel: "48小時前免費取消", origPrice: 3100, price: 2780 }
        ]
    },
    {
        id: 22,
        name: "Tosca di Angelo (香港麗思卡爾頓酒店)",
        district: "西九龍",
        location: "九龍柯士甸道西1號環球貿易廣場102樓",
        distance: "港鐵九龍站直達",
        images: ["https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.5,
        reviewCount: 2300,
        verdict: "雲端意饌",
        originalPrice: 2480,
        price: 2180,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: true,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r22_m1", name: "西西里地中海風情 5道菜海鮮晚市套餐", image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80", style: "西西里意式", drinks: "意大利精選氣泡酒", seating: "102樓無敵海景窗座", cancel: "24小時前免費取消", origPrice: 2480, price: 2180 }
        ]
    },
    {
        id: 23,
        name: "Estro",
        district: "中環",
        location: "中環都爹利街1號2樓",
        distance: "港鐵中環站步行約4分鐘",
        images: ["https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.3,
        reviewCount: 1150,
        verdict: "拿坡里詩篇",
        originalPrice: 2280,
        price: 1980,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: false,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r23_m1", name: "拿坡里紅泥窯烤與手工鈕扣麵品嚐盛宴", image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80", style: "當代南意料理", drinks: "南意大利火山土壤酒款搭配", seating: "紅磚典雅主廳", cancel: "24小時前免費取消", origPrice: 2280, price: 1980 }
        ]
    },
    {
        id: 24,
        name: "Octavium",
        district: "中環",
        location: "中環德輔道中22號One Chinachem Central 8樓",
        distance: "港鐵中環站步行約1分鐘",
        images: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.4,
        reviewCount: 1080,
        verdict: "低調私享",
        originalPrice: 2300,
        price: 2000,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: false,
        hasVegan: false,
        hasCancel: true,
        menus: [
            { id: "r24_m1", name: "主廚私房現代意式手工松露與野生魚料理", image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=600&q=80", style: "現代意式", drinks: "自然葡萄酒 Pairing", seating: "極簡現代主廳", cancel: "24小時前免費取消", origPrice: 2300, price: 2000 }
        ]
    },

    // ================= 創新融合 / 亞洲頂級概念料理 (Modern Fusion & Innovative) =================
    {
        id: 25,
        name: "TATE Dining Room",
        district: "上環",
        location: "上環荷李活道210號地下及1樓",
        distance: "港鐵上環站步行約6分鐘",
        images: ["https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80"],
        stars: 5,
        rating: 9.6,
        reviewCount: 1750,
        verdict: "頌歌美學",
        originalPrice: 2580,
        price: 2280,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: false,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r25_m1", name: "劉韻棋主廚「食物頌歌」中法融合 8道菜晚宴", image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80", style: "中法創新料理", drinks: "特調茶品及香檳搭配", seating: "粉調浪漫雅座", cancel: "24小時前免費取消", origPrice: 2580, price: 2280 }
        ]
    },
    {
        id: 26,
        name: "Andō",
        district: "中環",
        location: "中環威靈頓街52號Somptueux Central 1樓",
        distance: "港鐵中環站步行約4分鐘",
        images: ["https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.4,
        reviewCount: 1380,
        verdict: "西日交響",
        originalPrice: 2280,
        price: 1980,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: false,
        hasVegan: false,
        hasCancel: true,
        menus: [
            { id: "r26_m1", name: "阿根廷與日本靈魂融合 嘗味晚市菜單", image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80", style: "西日融合菜", drinks: "南美與日本精選佳釀", seating: "主廚料理吧台", cancel: "24小時前免費取消", origPrice: 2280, price: 1980 }
        ]
    },
    {
        id: 27,
        name: "Mono",
        district: "中環",
        location: "中環安蘭街18號5樓",
        distance: "港鐵中環站步行約3分鐘",
        images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.3,
        reviewCount: 1100,
        verdict: "南美當代",
        originalPrice: 2380,
        price: 2080,
        hasPrivateRoom: false,
        hasWindowSeat: true,
        hasParking: false,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r27_m1", name: "拉美風情與法式技藝 原創可可與海鮮盛宴", image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80", style: "拉丁美洲當代菜", drinks: "手工精品咖啡及南美酒", seating: "黑膠音樂主廳", cancel: "24小時前免費取消", origPrice: 2380, price: 2080 }
        ]
    },
    {
        id: 28,
        name: "Hansik Goo",
        district: "中環",
        location: "中環威靈頓街198號The Wellington 1樓",
        distance: "港鐵上環站步行約4分鐘",
        images: ["https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.2,
        reviewCount: 1250,
        verdict: "摩登韓饌",
        originalPrice: 1980,
        price: 1680,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: false,
        hasVegan: false,
        hasCancel: true,
        menus: [
            { id: "r28_m1", name: "首爾名廚 傳統宮廷韓食與當代創新品味晚宴", image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80", style: "當代精緻韓餐", drinks: "韓國傳統手工米酒 Pairing", seating: "原木韓式風格座", cancel: "24小時前免費取消", origPrice: 1980, price: 1680 }
        ]
    },
    {
        id: 29,
        name: "CHAAT (香港瑰麗酒店)",
        district: "尖沙咀",
        location: "尖沙咀梳士巴利道18號香港瑰麗酒店5樓",
        distance: "港鐵尖東站步行約3分鐘",
        images: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.4,
        reviewCount: 2100,
        verdict: "重塑印度街頭",
        originalPrice: 1888,
        price: 1588,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: true,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r29_m1", name: "經典泥爐炭烤羊排與印度香料珍饈晚宴", image: "https://images.unsplash.com/photo-1514326640560-7d063ef2aed5?auto=format&fit=crop&w=600&q=80", style: "頂級印度菜", drinks: "香料特調雞尾酒", seating: "維港露台海景座", cancel: "24小時前免費取消", origPrice: 1888, price: 1588 }
        ]
    },
    {
        id: 30,
        name: "New Punjab Club",
        district: "中環",
        location: "中環雲咸街34號世界商業大廈地下",
        distance: "港鐵中環站步行約5分鐘",
        images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.3,
        reviewCount: 1560,
        verdict: "旁遮普傳奇",
        originalPrice: 1980,
        price: 1680,
        hasPrivateRoom: false,
        hasWindowSeat: false,
        hasParking: false,
        hasVegan: false,
        hasCancel: false,
        menus: [
            { id: "r30_m1", name: "殖民時期俱樂部泥爐炭烤極品海鮮肉類套餐", image: "https://images.unsplash.com/photo-1514326640560-7d063ef2aed5?auto=format&fit=crop&w=600&q=80", style: "北印度烤肉", drinks: "頂級杜松子酒 Gin Tonic", seating: "復古皮質卡座", cancel: "特惠不可退", origPrice: 1980, price: 1680 }
        ]
    },
    {
        id: 31,
        name: "Mosu Hong Kong",
        district: "西九龍",
        location: "九龍西九文化區博物館道38號M+大樓3樓",
        distance: "港鐵九龍站步行約8分鐘",
        images: ["https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.5,
        reviewCount: 1480,
        verdict: "藝術殿堂",
        originalPrice: 2480,
        price: 2180,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: true,
        hasVegan: false,
        hasCancel: true,
        menus: [
            { id: "r31_m1", name: "首爾三星名廚 橡果麵與牛蒡皮藝術晚市套餐", image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80", style: "當代創新韓食", drinks: "藝術特選配酒", seating: "M+ 天台花園全景位", cancel: "48小時前免費取消", origPrice: 2480, price: 2180 }
        ]
    },
    {
        id: 32,
        name: "Arbor",
        district: "中環",
        location: "中環皇后大道中80號H Queen's 25樓",
        distance: "港鐵中環站步行約3分鐘",
        images: ["https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.4,
        reviewCount: 1350,
        verdict: "森林之美",
        originalPrice: 2388,
        price: 2088,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: false,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r32_m1", name: "北歐自然與日本高級食材 8 道菜交響晚宴", image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80", style: "北歐日式融合", drinks: "天然發酵果汁及酒款", seating: "25樓森林粉綠景觀席", cancel: "24小時前免費取消", origPrice: 2388, price: 2088 }
        ]
    },
    {
        id: 33,
        name: "The Steak House (香港麗晶酒店)",
        district: "尖沙咀",
        location: "尖沙咀梳士巴利道18號香港麗晶酒店地下",
        distance: "港鐵尖東站步行約3分鐘",
        images: ["https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80"],
        stars: 3,
        rating: 9.2,
        reviewCount: 2250,
        verdict: "肉食之巔",
        originalPrice: 2100,
        price: 1850,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: true,
        hasVegan: false,
        hasCancel: true,
        menus: [
            { id: "r33_m1", name: "炭火烤炙澳洲產 Mayura 和牛與奢華沙律吧晚宴", image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80", style: "頂級牛排館", drinks: "加州納帕谷赤霞珠紅酒", seating: "維港親水窗席", cancel: "24小時前免費取消", origPrice: 2100, price: 1850 }
        ]
    },
    {
        id: 34,
        name: "文華扒房+酒吧 (Mandarin Grill + Bar)",
        district: "中環",
        location: "中環干諾道中5號香港文華東方酒店1樓",
        distance: "港鐵中環站步行約2分鐘",
        images: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80"],
        stars: 4,
        rating: 9.3,
        reviewCount: 1980,
        verdict: "經典炭烤",
        originalPrice: 2200,
        price: 1900,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: true,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r34_m1", name: "主廚現代經典牛排與可持續海鮮 5道菜套餐", image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80", style: "經典扒房", drinks: "文華經典雞尾酒", seating: "傑拉德雕塑主廳", cancel: "24小時前免費取消", origPrice: 2200, price: 1900 }
        ]
    },
    {
        id: 35,
        name: "Magistracy Dining Room",
        district: "中環",
        location: "中環亞畢諾道1號大館中央裁判司署地下",
        distance: "港鐵中環站步行約6分鐘",
        images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80"],
        stars: 3,
        rating: 9.1,
        reviewCount: 1400,
        verdict: "英倫復古",
        originalPrice: 1950,
        price: 1680,
        hasPrivateRoom: true,
        hasWindowSeat: false,
        hasParking: false,
        hasVegan: true,
        hasCancel: true,
        menus: [
            { id: "r35_m1", name: "大館歷史建築 英倫傳統慢烤頂級牛肉晚餐", image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80", style: "英式傳統奢華", drinks: "英式傳統馬天尼", seating: "拱形穹頂主法庭廳", cancel: "24小時前免費取消", origPrice: 1950, price: 1680 }
        ]
    },
    {
        id: 36,
        name: "Carna by Dario Cecchini (Mondrian Hong Kong)",
        district: "尖沙咀",
        location: "尖沙咀赫德道8A號香港夢卓恩酒店39樓",
        distance: "港鐵尖東站步行約4分鐘",
        images: ["https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=800&q=80"],
        stars: 3,
        rating: 9.0,
        reviewCount: 920,
        verdict: "托斯卡納肉饌",
        originalPrice: 1850,
        price: 1580,
        hasPrivateRoom: true,
        hasWindowSeat: true,
        hasParking: false,
        hasVegan: false,
        hasCancel: true,
        menus: [
            { id: "r36_m1", name: "傳奇屠夫 從頭到尾 8道托斯卡納全牛盛宴", image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80", style: "意式牛排概念", drinks: "托斯卡納經典奇安蒂", seating: "39樓高空維港夜景座", cancel: "24小時前免費取消", origPrice: 1850, price: 1580 }
        ]
    }
];